############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[main]]
name = "Categories"
pageRef = "/categories"
weight = 3

[[main]]
name = "About"
pageRef = "/about"
weight = 4

# footer menu
[[footer]]
name = "Blog"
pageRef = "/blog"
weight = 1

[[footer]]
name = "Categories"
pageRef = "/categories"
weight = 2

[[footer]]
name = "About"
pageRef = "/about"
weight = 3
